server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/product_crud
    username: root
    password: lequanghuy2212
open:
  api:
    serverUrl: "http://localhost:8080/"
    serverName: "Development Server"
    title: "Product CRUD API"
    version: "1.0"
    description: "A simple CRUD API for managing products and categories using JWT"
api:
  prefix: "/api/v1"